export const STR = {
  UNKNOWN: "unknown",
  AddAliasOption:
    "Add new alias.\n" +
    " example:\n" +
    ' mkrtc alias -a alias1="cmd" - "description",alias2=[cmd]\n' +
    " Output:\n" +
    "  alias alias1=cmd\n" +
    "  alias alias2=cmd",
  ReadAliasOption: "Read aliases list",
  RemoveAliasOption: "Remove aliases",
  StateNotInitializedError: "state.json not initialized. Run: mkrtc --init",

  ReadSshOption: "Read saved ssh's list",
  RemoveSshOption: "Remove saved ssh by id",
  SaveSshConnectionOption: "Save connection",
  AliasAlreadyExistsError: (alias: string) =>
    `Alias "${alias}" already exists.`,
  AliasNotFoundError: (alias: string) => `Alias "${alias}" not found`,
  SshpassNorInstalledError:
    "sshpass not installed.\nRun sudo pacman -S sshpass",
  SshNameIsRequiredError: "--name is required!",
  SshNameIsDefinedError: (name: string) => `SSH "${name}" already exists`,
  SshConfigNotExistsError: (name: string) =>
    `Config with name "${name}" does not exists`,
} as const;

export const ENGLISH_CHARSET = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
];

export const Charset: Record<string, string[]> = {
  "A-Z": [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
  ],
  "a-z": [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
  ],
  "0-9": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
};
